# NumPy 
- NumPy 是 Numerical Python 的简称
- Python 中的科学计算基本软件包
- NumPy 为 Python 提供了大量数学库

- import numpy as np
- x.shap   
- x.dtype 
- x.size     

- np.save('myarray_y',y)
- np.load('myarray_y.npy')

- np.zeros((3,4))
- np.full(shape, constant value)
- np.eye(n) 会创建一个对应于单位矩阵的方形 N x N ndarray
- np.diag([10,20,30,50]) 对角矩阵是仅在主对角线上有值的方形矩阵。

- np.arange(start, stop, step) 
- np.linspace(start, stop, N) 
- np.reshape(ndarray, new_shape)

- np.random.random(shape) 
- np.random.randint(start, stop, size = shape) 

- np.random.normal(mean, standard deviation, size=shape)
- X[2, 2] 使用下标访问元素
- np.delete(ndarray, elements, axis)

- np.append(ndarray, elements, axis)
- np.insert(ndarray, index, elements, axis)

- nparray[start:end]
- np.copy()

- np.diag(ndarray, k=N)
- np.unique() 去重，返回一个列表

- X[X > 10] 布尔

- np.intersect1d(x,y)交集
- np.setdiff1d(x,y)差集
- np.union1d(x,y)并集

- np.unique(x) 去重
- np.sort() 排序


- np.add(x,y)
- np.subtract(x,y)
- np.multiply(x,y)
- np.divide(x,y)


- sqrt(array)
- np.exp(x)
- np.power(x,2)

- X.mean()
- X.sum()
- X.std()
- X.median()

- X.max(axis=0)
- X.min(axis=1)

### 导入
    import numpy as np

In [1]:
import numpy as np

### np.array数组 属性 类型
- x.shap   
- x.dtype   
    - .dtype 属性告诉我们 y 中的元素作为具有 8 个字符的 Unicode 字符串存储在内存中。
    - 如果同时提供整数和字符串的列表，NumPy会将所有元素解析为字符串。
- y.size     
- type(x)


In [21]:
x = np.array([1,2,3,4,5])
y = np.array(['nihao123','hello'])
print(x,y)

[1 2 3 4 5] ['nihao123' 'hello']


In [22]:
print(x.shape)# (5,)
print(type(x))# <class 'numpy.ndarray'>
print(x.dtype)# int32
print(y.dtype)# <U8  具有 8 个字符的 Unicode 字符串

(5,)
<class 'numpy.ndarray'>
int32
<U8


In [23]:
x = np.array([1, 2, 'World'])
print(x) # ['1' '2' 'World']

['1' '2' 'World']


In [29]:
y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]], dtype=np.int64)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### np.save ,np.load 保存和加载npy文件
- np.save('myarray_y',y)
- np.load('myarray_y.npy')

In [32]:
y.size
np.save('myarray_y',y)
z = np.load('myarray_y.npy')
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### np.zeros((3,4)) 快速创建np.array 数组
- 默认地创建一个 dtype 为 float64 的数组。你可以使用关键字 dtype 更改数据类型
    - X = np.zeros((3,4))
    
### np.full(shape, constant value) 创建指定shape、指定值的数组
- np.full(shape, constant value) 函数有两个参数。
    - 第一个参数是你要创建的 ndarray 的形状，
    - 第二个参数是你要向数组中填充的常数值
    - X = np.full((2,3), 5) 

In [38]:
X = np.full((2,3), 5, dtype=np.int64) 
X

array([[5, 5, 5],
       [5, 5, 5]], dtype=int64)

### np.eye(n) 会创建一个对应于单位矩阵的方形 N x N ndarray

In [40]:
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.diag([10,20,30,50]) 对角矩阵是仅在主对角线上有值的方形矩阵。

In [41]:
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

### np.arange()
#### np.arange(start, stop, step) 
- 均匀分布的数字将包括 start 数字，但是不包括 stop 数字
- 虽然 np.arange() 函数允许间隔为非整数，例如 0.3，但是由于浮点数精度有限，输出通常不一致。因此，如果需要非整数间隔，通常建议使用函数 np.linspace()
### np.linspace(start, stop, N) 
-  函数返回 N 个在闭区间 [start, stop] 内均匀分布的数字。
### np.reshape(ndarray, new_shape)

In [42]:
x = np.linspace(0,25,10, endpoint = False)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [43]:
x = np.arange(1,14,3)
x

array([ 1,  4,  7, 10, 13])

In [47]:
# Y = np.arange(20).reshape(4, 5) 写成一行

x = np.arange(20)
x = np.reshape(x, (4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

### np.random.random(shape) 
- 创建具有给定形状的 ndarray，其中包含位于半开区间 [0.0, 1.0) 内的随机浮点数。
### np.random.randint(start, stop, size = shape) 
- 创建一个具有给定形状的 ndarray，其中包含在半开区间 [start, stop) 内的随机整数

In [49]:
X = np.random.randint(4,15,size=(3,2))
X

array([[12,  4],
       [ 6, 10],
       [ 4,  8]])

### np.random.normal(mean, standard deviation, size=shape)
- 会创建一个具有给定形状的 ndarray，其中包含从正态高斯分布（具有给定均值和标准差）中抽样的随机数字。
- 创建一个 1,000 x 1,000 ndarray，其中包含从正态分布（均值为 0，标准差为 0.1）中随机抽样的浮点数。

In [52]:
X = np.random.normal(0, 0.1, size=(1000,1000))
print('shape:', X.shape)
print('X type:', type(X))
print('dtype:', X.dtype)
print('mean :', X.mean())
print('maximum:', X.max())
print('minimum:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

shape: (1000, 1000)
X type: <class 'numpy.ndarray'>
dtype: float64
mean : -0.0001103612497113915
maximum: 0.47577106071975406
minimum: -0.4424793490060228
X has 500142 negative numbers
X has 499858 positive numbers


### X[2, 2] 使用下标访问元素

In [54]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[0,1]

2

### np.delete(ndarray, elements, axis)
- 删除元素
- 整行整列的删除元素
- axis = 0 表示选择行，axis = 1 表示选择列

In [62]:
x = np.array([1, 2, 3, 4, 5])
x = np.delete(x, [0,2,4]) 
x

array([2, 4])

In [64]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
w = np.delete(Y, 0, axis=0)
w

array([[4, 5, 6],
       [7, 8, 9]])

### np.append(ndarray, elements, axis)
- 添加

In [65]:
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
x

array([1, 2, 3, 4, 5, 6])

In [71]:
Y = np.array([[1,2,3],[4,5,6],[2,2,2]])

# 加行
# v = np.append(Y, [[7,8,9]], axis=0)

v = np.append(Y, [[7],[8],[9]], axis=1)
v

array([[1, 2, 3, 7],
       [4, 5, 6, 8],
       [2, 2, 2, 9]])

### np.insert(ndarray, index, elements, axis)
- 插入

In [72]:
Y = np.array([[1,2,3],[7,8,9]])
w = np.insert(Y,1,[4,5,6],axis=0)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 切片
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [73]:
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
Z = X[1:4,2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [76]:
W = X[1:,2:]
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [78]:
Y = X[:3,2:]
Y

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [79]:
v = X[2,:] # 整行
v

array([10, 11, 12, 13, 14])

In [80]:
q = X[:,2] # 整列
q

array([ 2,  7, 12, 17])

## np.copy()
- 切片后的数组依然指向原来的数组，对其修改会改变原数组
- 所以，将切片作为新数组，需要用到copy()函数

In [81]:
X = np.arange(20).reshape(4, 5)
Z = X[1:4,2:5]
Z[2,2] = 555
X

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 555]])

In [82]:
W = X[1:4,2:5].copy()
W[2,2] = 444
X

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 555]])

In [83]:
W

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 444]])

### np.diag(ndarray, k=N)
- 函数会以 N 定义的对角线提取元素。
- 默认情况下，k=0，表示主对角线。k > 0 的值用于选择在主对角线之上的对角线中的元素，k < 0 的值用于选择在主对角线之下的对角线中的元素

In [84]:
X = np.arange(25).reshape(5, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [87]:
z = np.diag(X, k=1)
z

array([ 1,  7, 13, 19])

### np.unique() 提取唯一的元素

In [89]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print('unique:',np.unique(X))

unique: [1 2 3 5 8]


### 布尔型索引、集合运算和排序
### X[X > 10] 布尔
### 集合
- np.intersect1d(x,y)交集
- np.setdiff1d(x,y)差集
- np.union1d(x,y)并集

In [95]:
X = np.arange(25).reshape(5, 5)
X[X > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [96]:
X[(X > 10) & (X < 17)] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  0,  0,  0,  0],
       [ 0,  0, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


### np.sort() 排序

In [98]:
x = np.random.randint(1,11,size=(10,))
x

array([ 3,  6,  2,  1,  9, 10,  9,  5,  9,  8])

In [99]:
np.sort(x)

array([ 1,  2,  3,  5,  6,  8,  9,  9,  9, 10])

In [100]:
x

array([ 3,  6,  2,  1,  9, 10,  9,  5,  9,  8])

### np.unique(x) 去重

In [101]:
np.sort(np.unique(x))

array([ 1,  2,  3,  5,  6,  8,  9, 10])

### np.sort(X, axis = 0) 按行还是按列排序？

In [105]:
X = np.random.randint(1,11,size=(5,5))
print('Original X = \n', X)
print('X with sorted columns :\n', np.sort(X, axis = 0))
print('X with sorted rows :\n', np.sort(X, axis = 1))

Original X = 
 [[ 4  7  7  2  4]
 [10  2  8  2 10]
 [ 5  4  5 10  6]
 [ 4  1  5  1  2]
 [ 2  6  7  6  5]]
X with sorted columns :
 [[ 2  1  5  1  2]
 [ 4  2  5  2  4]
 [ 4  4  7  2  5]
 [ 5  6  7  6  6]
 [10  7  8 10 10]]
X with sorted rows :
 [[ 2  4  4  7  7]
 [ 2  2  8 10 10]
 [ 4  5  5  6 10]
 [ 1  1  2  4  5]
 [ 2  5  6  6  7]]


## 算术运算和广播
### 对array每个元素进行算术运算
- np.add(x,y)
- np.subtract(x,y)
- np.multiply(x,y)
- np.divide(x,y)

In [106]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
np.add(x,y)  

# x + y

array([ 6.5,  8.5, 10.5, 12.5])

### 对维度相同的array可以执行算术操作

In [107]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print('X + Y = \n', X + Y)

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]


### sqrt(array)
### np.exp(x)
### np.power(x,2)

In [108]:
x = np.array([1,2,3,4])
print('EXP(x) =', np.exp(x)) # 欧拉系数
print('SQRT(x) =',np.sqrt(x)) # 平方根
print('POW(x,2) =',np.power(x,2)) # 平方

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
SQRT(x) = [1.         1.41421356 1.73205081 2.        ]
POW(x,2) = [ 1  4  9 16]


### 平均数
- X.mean()
- X.mean(axis=0)
- X.mean(axis=1)
### 求和
- X.sum()
- X.sum(axis=0)
- X.sum(axis=1)
### 最大值，最小值，X.max(axis=0), X.min(axis=1)
### 标准差X.std()，
### 中位数X.median()

### 可以对两个形状不同的 ndarray 执行相同的操作

In [111]:
x = np.array([1,2,3])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z = np.array([1,2,3]).reshape(3,1)

print('x = ', x)
print()
print('Y = \n', Y)
print()
print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)

x =  [1 2 3]

Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
